///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest24
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest24Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("5fe1c13d-6ee7-4d1d-9c94-bda149aef246")]
    public partial class MyTest24Repository : RepoGenBaseFolder
    {
        static MyTest24Repository instance = new MyTest24Repository();

        /// <summary>
        /// Gets the singleton class instance representing the MyTest24Repository element repository.
        /// </summary>
        [RepositoryFolder("5fe1c13d-6ee7-4d1d-9c94-bda149aef246")]
        public static MyTest24Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest24Repository() 
            : base("MyTest24Repository", "/", null, 0, false, "5fe1c13d-6ee7-4d1d-9c94-bda149aef246", ".\\RepositoryImages\\MyTest24Repository5fe1c13d.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("5fe1c13d-6ee7-4d1d-9c94-bda149aef246")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest24RepositoryFolders
    {
    }
#pragma warning restore 0436
}
